/*
 * Created on 2023-05-24 ( 16:59:34 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.lct.entities;

import java.io.Serializable;
import java.util.List;
import javax.persistence.*;

/**
 * JPA entity class for "Account"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="account", schema="dbo", catalog="chicken_app" )
public class Account implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="username", nullable=false, length=45)
    private String     username ;

    //--- ENTITY DATA FIELDS 
    @Column(name="fullname", nullable=false, length=100)
    private String     fullname ;

    @Column(name="email", nullable=false, length=45)
    private String     email ;

    @Column(name="nphone", nullable=false, length=45)
    private String     nphone ;

    @Column(name="password", nullable=false, length=45)
    private String     password ;

    @Column(name="address", nullable=false, length=45)
    private String     address ;

    @Column(name="photo", length=45)
    private String     photo ;

    @Column(name="role", nullable=false)
    private Boolean    role ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="account")
    private List<Order> listOfOrder ; 


    /**
     * Constructor
     */
    public Account() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setUsername( String username ) {
        this.username = username ;
    }
    public String getUsername() {
        return this.username;
    }

    public void setFullname( String fullname ) {
        this.fullname = fullname ;
    }
    public String getFullname() {
        return this.fullname;
    }

    public void setEmail( String email ) {
        this.email = email ;
    }
    public String getEmail() {
        return this.email;
    }

    public void setNphone( String nphone ) {
        this.nphone = nphone ;
    }
    public String getNphone() {
        return this.nphone;
    }

    public void setPassword( String password ) {
        this.password = password ;
    }
    public String getPassword() {
        return this.password;
    }

    public void setAddress( String address ) {
        this.address = address ;
    }
    public String getAddress() {
        return this.address;
    }

    public void setPhoto( String photo ) {
        this.photo = photo ;
    }
    public String getPhoto() {
        return this.photo;
    }

    public void setRole( Boolean role ) {
        this.role = role ;
    }
    public Boolean getRole() {
        return this.role;
    }
    

    public void setListOfOrder(List<Order> listOfOrder) {
		this.listOfOrder = listOfOrder;
	}

	//--- GETTERS FOR LINKS
    public List<Order> getListOfOrder() {
        return this.listOfOrder;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(username);
        sb.append("|");
        sb.append(fullname);
        sb.append("|");
        sb.append(email);
        sb.append("|");
        sb.append(nphone);
        sb.append("|");
        sb.append(password);
        sb.append("|");
        sb.append(address);
        sb.append("|");
        sb.append(photo);
        sb.append("|");
        sb.append(role);
        return sb.toString(); 
    } 

}
