/*
 * Created on 2023-05-24 ( 16:59:34 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.lct.entities;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import javax.persistence.*;


/**
 * JPA entity class for "Order"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="[order]", schema="dbo", catalog="chicken_app" )
public class Order implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Long    id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="userid", nullable=false, length=45)
    private String     userid ;

    @Column(name="total_price", nullable=false)
    private Double     totalPrice ;

    @Column(name="nphone", nullable=false, length=45)
    private String     nphone ;
    
    @Column(name="orderstatus", nullable=false, length=45)
    private Integer     orderStatus ;

	public Integer getOrderStatus() {
		return orderStatus;
	}

	public void setOrderStatus(Integer orderStatus) {
		this.orderStatus = orderStatus;
	}

	public void setListOfOrderDetail(List<OrderDetail> listOfOrderDetail) {
		this.listOfOrderDetail = listOfOrderDetail;
	}

	@Temporal(TemporalType.DATE)
    @Column(name="[date]", nullable=false)
    private Date       date = new Date();

    @Column(name="[address]", nullable=false, length=45)
    private String     address ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="userid", referencedColumnName="username", insertable=false, updatable=false)
    private Account    account ; 

    @OneToMany(mappedBy="order")
    private List<OrderDetail> listOfOrderDetail ; 


    /**
     * Constructor
     */
    public Order() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Long id ) {
        this.id = id ;
    }
    public Long getId() {
        return this.id;
    }

    public void setUserid( String userid ) {
        this.userid = userid ;
    }
    public String getUserid() {
        return this.userid;
    }

    public void setTotalPrice( Double totalPrice ) {
        this.totalPrice = totalPrice ;
    }
    public Double getTotalPrice() {
        return this.totalPrice;
    }

    public void setNphone( String nphone ) {
        this.nphone = nphone ;
    }
    public String getNphone() {
        return this.nphone;
    }

    public void setDate( Date date ) {
        this.date = date ;
    }
    public Date getDate() {
        return this.date;
    }

    public void setAddress( String address ) {
        this.address = address ;
    }
    public String getAddress() {
        return this.address;
    }

    public void setAccount(Account account) {
		this.account = account;
	}
    
    //--- GETTERS FOR LINKS
    public Account getAccount() {
        return this.account;
    } 

    public List<OrderDetail> getListOfOrderDetail() {
        return this.listOfOrderDetail;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(userid);
        sb.append("|");
        sb.append(totalPrice);
        sb.append("|");
        sb.append(nphone);
        sb.append("|");
        sb.append(date);
        sb.append("|");
        sb.append(address);
        return sb.toString(); 
    } 

}
