/*
 * Created on 2023-05-24 ( 16:59:34 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.lct.entities;

import java.io.Serializable;
import javax.persistence.*;

/**
 * JPA entity class for "OrderDetail"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="order_detail", schema="dbo", catalog="chicken_app" )
public class OrderDetail implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Long    id ;

    @Column(name="quantity", nullable=false)
    private Integer    quantity ;

    @Column(name="price", nullable=false)
    private Double     price ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="orderid")
    private Order      order ; 

    @ManyToOne
    @JoinColumn(name="productid")
    private Product    product ; 


    /**
     * Constructor
     */
    public OrderDetail() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Long id ) {
        this.id = id ;
    }
    public Long getId() {
        return this.id;
    }

    public void setQuantity( Integer quantity ) {
        this.quantity = quantity ;
    }
    public Integer getQuantity() {
        return this.quantity;
    }

    public void setPrice( Double price ) {
        this.price = price ;
    }
    public Double getPrice() {
        return this.price;
    }

    //--- GETTERS FOR LINKS
    public Order getOrder() {
        return this.order;
    } 

    public Product getProduct() {
        return this.product;
    } 

    public void setOrder(Order order) {
		this.order = order;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	//--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(quantity);
        sb.append("|");
        sb.append(price);
        return sb.toString(); 
    } 

}
