/*
 * Created on 2023-05-24 ( 16:59:34 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.lct.entities;

import java.io.Serializable;
import java.sql.Date;
import java.util.List;
import javax.persistence.*;

/**
 * JPA entity class for "Product"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="product", schema="dbo", catalog="chicken_app" )
public class Product implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="productid", nullable=false)
    private Long    productid ;

    //--- ENTITY DATA FIELDS 
    @Column(name="product_name", nullable=false, length=45)
    private String     productName ;

    @Column(name="price", nullable=false)
    private Double     price ;

    @Column(name="categoryid", nullable=false, length=45)
    private String     categoryid ;

    @Column(name="createdate", nullable=false)
    private Date       createdate ;

    @Column(name="describe", nullable=false, length=500)
    private String     describe ;

    @Column(name="quantity", nullable=false)
    private Integer    quantity ;

    @Column(name="photo", nullable=false, length=200)
    private String     photo ;

    @Column(name="khuyenmai", nullable=false, length=200)
    private String     khuyenmai ;

    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="product")
    private List<OrderDetail> listOfOrderDetail ; 

    @ManyToOne
    @JoinColumn(name="categoryid", referencedColumnName="categoryid", insertable=false, updatable=false)
    private Category   category ; 


    /**
     * Constructor
     */
    public Product() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setProductid( Long productid ) {
        this.productid = productid ;
    }
    public Long getProductid() {
        return this.productid;
    }

    public void setProductName( String productName ) {
        this.productName = productName ;
    }
    public String getProductName() {
        return this.productName;
    }

    public void setPrice( Double price ) {
        this.price = price ;
    }
    public Double getPrice() {
        return this.price;
    }

    public void setCategoryid( String categoryid ) {
        this.categoryid = categoryid ;
    }
    public String getCategoryid() {
        return this.categoryid;
    }

    public void setCreatedate( Date createdate ) {
        this.createdate = createdate ;
    }
    public Date getCreatedate() {
        return this.createdate;
    }

    public void setDescribe( String describe ) {
        this.describe = describe ;
    }
    public String getDescribe() {
        return this.describe;
    }

    public void setQuantity( Integer quantity ) {
        this.quantity = quantity ;
    }
    public Integer getQuantity() {
        return this.quantity;
    }

    public void setPhoto( String photo ) {
        this.photo = photo ;
    }
    public String getPhoto() {
        return this.photo;
    }
    
    public void setKhuyenmai( String khuyenmai ) {
        this.khuyenmai = khuyenmai ;
    }
    public String getKhuyenmai() {
        return this.khuyenmai;
    }

    //--- GETTERS FOR LINKS
    public List<OrderDetail> getListOfOrderDetail() {
        return this.listOfOrderDetail;
    } 

    public Category getCategory() {
        return this.category;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(productid);
        sb.append("|");
        sb.append(productName);
        sb.append("|");
        sb.append(price);
        sb.append("|");
        sb.append(categoryid);
        sb.append("|");
        sb.append(createdate);
        sb.append("|");
        sb.append(describe);
        sb.append("|");
        sb.append(quantity);
        sb.append("|");
        sb.append(photo);
        return sb.toString(); 
    } 

}
