/*
 * Created on 2023-05-24 ( 16:59:34 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.lct.entities;

import java.io.Serializable;
import javax.persistence.*;

/**
 * JPA entity class for "Sysdiagrams"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="sysdiagrams", schema="dbo", catalog="chicken_app" )
public class Sysdiagrams implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="diagram_id", nullable=false)
    private Integer    diagramId ;

    //--- ENTITY DATA FIELDS 
    @Column(name="name", nullable=false, length=128)
    private String     name ;

    @Column(name="principal_id", nullable=false)
    private Integer    principalId ;

    @Column(name="version")
    private Integer    version ;

    @Lob
    @Column(name="definition")
    private byte[]     definition ;


    //--- ENTITY LINKS ( RELATIONSHIP )

    /**
     * Constructor
     */
    public Sysdiagrams() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setDiagramId( Integer diagramId ) {
        this.diagramId = diagramId ;
    }
    public Integer getDiagramId() {
        return this.diagramId;
    }

    public void setName( String name ) {
        this.name = name ;
    }
    public String getName() {
        return this.name;
    }

    public void setPrincipalId( Integer principalId ) {
        this.principalId = principalId ;
    }
    public Integer getPrincipalId() {
        return this.principalId;
    }

    public void setVersion( Integer version ) {
        this.version = version ;
    }
    public Integer getVersion() {
        return this.version;
    }

    public void setDefinition( byte[] definition ) {
        this.definition = definition ;
    }
    public byte[] getDefinition() {
        return this.definition;
    }

    //--- GETTERS FOR LINKS
    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(diagramId);
        sb.append("|");
        sb.append(name);
        sb.append("|");
        sb.append(principalId);
        sb.append("|");
        sb.append(version);
        // attribute 'definition' not usable (type = byte[])
        return sb.toString(); 
    } 

}
